[server]
host = "localhost"
#host = "" # Docker
port = 8080

[content]
not_found = "/not-found"

[sass]
dir = "assets"
entrypoint = "style.scss"
out = "assets/style.css"
out_source_map = "assets/style.css.map"
watch = true
compiler = "C:/Users/marvi/sass_embedded/dart-sass-embedded.bat"
#compiler = "dart-sass-embedded" # Docker

[js]
dir = "assets"
entrypoint = "entrypoint.js"
out = "assets/bundle.js"
out_source_map = "assets/bundle.js.map"
watch = true
